// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novel_writer.proto

package p2pws.novel;

public interface NovelWriterCommandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p2pws.novel.NovelWriterCommandResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.p2pws.novel.NovelWriterCommandResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.p2pws.novel.NovelWriterCommandResponse.Status status = 1;</code>
   * @return The status.
   */
  p2pws.novel.NovelWriterCommandResponse.Status getStatus();

  /**
   * <pre>
   * 错误信息或补充描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 错误信息或补充描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 异步任务时返回的 ID
   * </pre>
   *
   * <code>string task_id = 3;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * 异步任务时返回的 ID
   * </pre>
   *
   * <code>string task_id = 3;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * 命令结果（结构化字段）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue result = 4;</code>
   */
  java.util.List<p2pws.novel.KeyValue> 
      getResultList();
  /**
   * <pre>
   * 命令结果（结构化字段）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue result = 4;</code>
   */
  p2pws.novel.KeyValue getResult(int index);
  /**
   * <pre>
   * 命令结果（结构化字段）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue result = 4;</code>
   */
  int getResultCount();
  /**
   * <pre>
   * 命令结果（结构化字段）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue result = 4;</code>
   */
  java.util.List<? extends p2pws.novel.KeyValueOrBuilder> 
      getResultOrBuilderList();
  /**
   * <pre>
   * 命令结果（结构化字段）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue result = 4;</code>
   */
  p2pws.novel.KeyValueOrBuilder getResultOrBuilder(
      int index);
}
