// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novel_writer.proto

package p2pws.novel;

public interface NovelWriterEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p2pws.novel.NovelWriterEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.p2pws.novel.NovelWriterEvent.Severity severity = 1;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.p2pws.novel.NovelWriterEvent.Severity severity = 1;</code>
   * @return The severity.
   */
  p2pws.novel.NovelWriterEvent.Severity getSeverity();

  /**
   * <pre>
   * 对齐 WorkflowEvent.EventType 名字（AGENT_STREAMING / CHAPTER_WRITTEN / PLANNING_DONE / ...）
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * 对齐 WorkflowEvent.EventType 名字（AGENT_STREAMING / CHAPTER_WRITTEN / PLANNING_DONE / ...）
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <pre>
   * 项目/章节上下文
   * </pre>
   *
   * <code>string project_id = 3;</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <pre>
   * 项目/章节上下文
   * </pre>
   *
   * <code>string project_id = 3;</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();

  /**
   * <code>string chapter_id = 4;</code>
   * @return The chapterId.
   */
  java.lang.String getChapterId();
  /**
   * <code>string chapter_id = 4;</code>
   * @return The bytes for chapterId.
   */
  com.google.protobuf.ByteString
      getChapterIdBytes();

  /**
   * <pre>
   * 原始 payload（业务字段，键值对）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue payload = 5;</code>
   */
  java.util.List<p2pws.novel.KeyValue> 
      getPayloadList();
  /**
   * <pre>
   * 原始 payload（业务字段，键值对）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue payload = 5;</code>
   */
  p2pws.novel.KeyValue getPayload(int index);
  /**
   * <pre>
   * 原始 payload（业务字段，键值对）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue payload = 5;</code>
   */
  int getPayloadCount();
  /**
   * <pre>
   * 原始 payload（业务字段，键值对）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue payload = 5;</code>
   */
  java.util.List<? extends p2pws.novel.KeyValueOrBuilder> 
      getPayloadOrBuilderList();
  /**
   * <pre>
   * 原始 payload（业务字段，键值对）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue payload = 5;</code>
   */
  p2pws.novel.KeyValueOrBuilder getPayloadOrBuilder(
      int index);

  /**
   * <pre>
   * 关联任务 ID（异步任务的进度事件时使用）
   * </pre>
   *
   * <code>string task_id = 6;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * 关联任务 ID（异步任务的进度事件时使用）
   * </pre>
   *
   * <code>string task_id = 6;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp_ms = 7;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
