// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novel_writer.proto

package p2pws.novel;

public final class NovelWriter {
  private NovelWriter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p2pws_novel_NovelWriterCommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p2pws_novel_NovelWriterCommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p2pws_novel_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p2pws_novel_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p2pws_novel_NovelWriterCommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p2pws_novel_NovelWriterCommandResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p2pws_novel_NovelWriterEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p2pws_novel_NovelWriterEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022novel_writer.proto\022\013p2pws.novel\"|\n\031Nov" +
      "elWriterCommandRequest\022\022\n\ncommand_id\030\001 \001" +
      "(\t\022\022\n\nproject_id\030\002 \001(\t\022\022\n\nchapter_id\030\003 \001" +
      "(\t\022#\n\004args\030\004 \003(\0132\025.p2pws.novel.KeyValue\"" +
      "&\n\010KeyValue\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"" +
      "\335\001\n\032NovelWriterCommandResponse\022>\n\006status" +
      "\030\001 \001(\0162..p2pws.novel.NovelWriterCommandR" +
      "esponse.Status\022\017\n\007message\030\002 \001(\t\022\017\n\007task_" +
      "id\030\003 \001(\t\022%\n\006result\030\004 \003(\0132\025.p2pws.novel.K" +
      "eyValue\"6\n\006Status\022\013\n\007UNKNOWN\020\000\022\006\n\002OK\020\001\022\013" +
      "\n\007RUNNING\020\002\022\n\n\006FAILED\020\003\"\202\002\n\020NovelWriterE" +
      "vent\0228\n\010severity\030\001 \001(\0162&.p2pws.novel.Nov" +
      "elWriterEvent.Severity\022\022\n\nevent_type\030\002 \001" +
      "(\t\022\022\n\nproject_id\030\003 \001(\t\022\022\n\nchapter_id\030\004 \001" +
      "(\t\022&\n\007payload\030\005 \003(\0132\025.p2pws.novel.KeyVal" +
      "ue\022\017\n\007task_id\030\006 \001(\t\022\024\n\014timestamp_ms\030\007 \001(" +
      "\003\")\n\010Severity\022\010\n\004INFO\020\000\022\010\n\004WARN\020\001\022\t\n\005ERR" +
      "OR\020\002B\017\n\013p2pws.novelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_p2pws_novel_NovelWriterCommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p2pws_novel_NovelWriterCommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p2pws_novel_NovelWriterCommandRequest_descriptor,
        new java.lang.String[] { "CommandId", "ProjectId", "ChapterId", "Args", });
    internal_static_p2pws_novel_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_p2pws_novel_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p2pws_novel_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_p2pws_novel_NovelWriterCommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_p2pws_novel_NovelWriterCommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p2pws_novel_NovelWriterCommandResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "TaskId", "Result", });
    internal_static_p2pws_novel_NovelWriterEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_p2pws_novel_NovelWriterEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p2pws_novel_NovelWriterEvent_descriptor,
        new java.lang.String[] { "Severity", "EventType", "ProjectId", "ChapterId", "Payload", "TaskId", "TimestampMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
