// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novel_writer.proto

package p2pws.novel;

/**
 * Protobuf type {@code p2pws.novel.NovelWriterCommandRequest}
 */
public final class NovelWriterCommandRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:p2pws.novel.NovelWriterCommandRequest)
    NovelWriterCommandRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NovelWriterCommandRequest.newBuilder() to construct.
  private NovelWriterCommandRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NovelWriterCommandRequest() {
    commandId_ = "";
    projectId_ = "";
    chapterId_ = "";
    args_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NovelWriterCommandRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NovelWriterCommandRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            commandId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            projectId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            chapterId_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              args_ = new java.util.ArrayList<p2pws.novel.KeyValue>();
              mutable_bitField0_ |= 0x00000001;
            }
            args_.add(
                input.readMessage(p2pws.novel.KeyValue.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        args_ = java.util.Collections.unmodifiableList(args_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return p2pws.novel.NovelWriter.internal_static_p2pws_novel_NovelWriterCommandRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return p2pws.novel.NovelWriter.internal_static_p2pws_novel_NovelWriterCommandRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            p2pws.novel.NovelWriterCommandRequest.class, p2pws.novel.NovelWriterCommandRequest.Builder.class);
  }

  public static final int COMMAND_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object commandId_;
  /**
   * <pre>
   * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
   * </pre>
   *
   * <code>string command_id = 1;</code>
   * @return The commandId.
   */
  @java.lang.Override
  public java.lang.String getCommandId() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
   * </pre>
   *
   * <code>string command_id = 1;</code>
   * @return The bytes for commandId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandIdBytes() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROJECT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object projectId_;
  /**
   * <pre>
   * 命令上下文（部分命令需要）
   * </pre>
   *
   * <code>string project_id = 2;</code>
   * @return The projectId.
   */
  @java.lang.Override
  public java.lang.String getProjectId() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 命令上下文（部分命令需要）
   * </pre>
   *
   * <code>string project_id = 2;</code>
   * @return The bytes for projectId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectIdBytes() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAPTER_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object chapterId_;
  /**
   * <code>string chapter_id = 3;</code>
   * @return The chapterId.
   */
  @java.lang.Override
  public java.lang.String getChapterId() {
    java.lang.Object ref = chapterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chapterId_ = s;
      return s;
    }
  }
  /**
   * <code>string chapter_id = 3;</code>
   * @return The bytes for chapterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChapterIdBytes() {
    java.lang.Object ref = chapterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chapterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARGS_FIELD_NUMBER = 4;
  private java.util.List<p2pws.novel.KeyValue> args_;
  /**
   * <pre>
   * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
   */
  @java.lang.Override
  public java.util.List<p2pws.novel.KeyValue> getArgsList() {
    return args_;
  }
  /**
   * <pre>
   * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends p2pws.novel.KeyValueOrBuilder> 
      getArgsOrBuilderList() {
    return args_;
  }
  /**
   * <pre>
   * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
   */
  @java.lang.Override
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <pre>
   * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
   */
  @java.lang.Override
  public p2pws.novel.KeyValue getArgs(int index) {
    return args_.get(index);
  }
  /**
   * <pre>
   * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
   * </pre>
   *
   * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
   */
  @java.lang.Override
  public p2pws.novel.KeyValueOrBuilder getArgsOrBuilder(
      int index) {
    return args_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCommandIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commandId_);
    }
    if (!getProjectIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, projectId_);
    }
    if (!getChapterIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, chapterId_);
    }
    for (int i = 0; i < args_.size(); i++) {
      output.writeMessage(4, args_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCommandIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commandId_);
    }
    if (!getProjectIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, projectId_);
    }
    if (!getChapterIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, chapterId_);
    }
    for (int i = 0; i < args_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, args_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof p2pws.novel.NovelWriterCommandRequest)) {
      return super.equals(obj);
    }
    p2pws.novel.NovelWriterCommandRequest other = (p2pws.novel.NovelWriterCommandRequest) obj;

    if (!getCommandId()
        .equals(other.getCommandId())) return false;
    if (!getProjectId()
        .equals(other.getProjectId())) return false;
    if (!getChapterId()
        .equals(other.getChapterId())) return false;
    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommandId().hashCode();
    hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProjectId().hashCode();
    hash = (37 * hash) + CHAPTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChapterId().hashCode();
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static p2pws.novel.NovelWriterCommandRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(p2pws.novel.NovelWriterCommandRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code p2pws.novel.NovelWriterCommandRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p2pws.novel.NovelWriterCommandRequest)
      p2pws.novel.NovelWriterCommandRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return p2pws.novel.NovelWriter.internal_static_p2pws_novel_NovelWriterCommandRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return p2pws.novel.NovelWriter.internal_static_p2pws_novel_NovelWriterCommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              p2pws.novel.NovelWriterCommandRequest.class, p2pws.novel.NovelWriterCommandRequest.Builder.class);
    }

    // Construct using p2pws.novel.NovelWriterCommandRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getArgsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      commandId_ = "";

      projectId_ = "";

      chapterId_ = "";

      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        argsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return p2pws.novel.NovelWriter.internal_static_p2pws_novel_NovelWriterCommandRequest_descriptor;
    }

    @java.lang.Override
    public p2pws.novel.NovelWriterCommandRequest getDefaultInstanceForType() {
      return p2pws.novel.NovelWriterCommandRequest.getDefaultInstance();
    }

    @java.lang.Override
    public p2pws.novel.NovelWriterCommandRequest build() {
      p2pws.novel.NovelWriterCommandRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public p2pws.novel.NovelWriterCommandRequest buildPartial() {
      p2pws.novel.NovelWriterCommandRequest result = new p2pws.novel.NovelWriterCommandRequest(this);
      int from_bitField0_ = bitField0_;
      result.commandId_ = commandId_;
      result.projectId_ = projectId_;
      result.chapterId_ = chapterId_;
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.args_ = args_;
      } else {
        result.args_ = argsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof p2pws.novel.NovelWriterCommandRequest) {
        return mergeFrom((p2pws.novel.NovelWriterCommandRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(p2pws.novel.NovelWriterCommandRequest other) {
      if (other == p2pws.novel.NovelWriterCommandRequest.getDefaultInstance()) return this;
      if (!other.getCommandId().isEmpty()) {
        commandId_ = other.commandId_;
        onChanged();
      }
      if (!other.getProjectId().isEmpty()) {
        projectId_ = other.projectId_;
        onChanged();
      }
      if (!other.getChapterId().isEmpty()) {
        chapterId_ = other.chapterId_;
        onChanged();
      }
      if (argsBuilder_ == null) {
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
      } else {
        if (!other.args_.isEmpty()) {
          if (argsBuilder_.isEmpty()) {
            argsBuilder_.dispose();
            argsBuilder_ = null;
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000001);
            argsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArgsFieldBuilder() : null;
          } else {
            argsBuilder_.addAllMessages(other.args_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      p2pws.novel.NovelWriterCommandRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (p2pws.novel.NovelWriterCommandRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object commandId_ = "";
    /**
     * <pre>
     * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
     * </pre>
     *
     * <code>string command_id = 1;</code>
     * @return The commandId.
     */
    public java.lang.String getCommandId() {
      java.lang.Object ref = commandId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
     * </pre>
     *
     * <code>string command_id = 1;</code>
     * @return The bytes for commandId.
     */
    public com.google.protobuf.ByteString
        getCommandIdBytes() {
      java.lang.Object ref = commandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
     * </pre>
     *
     * <code>string command_id = 1;</code>
     * @param value The commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commandId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
     * </pre>
     *
     * <code>string command_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandId() {
      
      commandId_ = getDefaultInstance().getCommandId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务命令名（大写下划线），例如 CREATE_PROJECT / START_PLANNING / WRITE_CHAPTER
     * </pre>
     *
     * <code>string command_id = 1;</code>
     * @param value The bytes for commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commandId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object projectId_ = "";
    /**
     * <pre>
     * 命令上下文（部分命令需要）
     * </pre>
     *
     * <code>string project_id = 2;</code>
     * @return The projectId.
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 命令上下文（部分命令需要）
     * </pre>
     *
     * <code>string project_id = 2;</code>
     * @return The bytes for projectId.
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 命令上下文（部分命令需要）
     * </pre>
     *
     * <code>string project_id = 2;</code>
     * @param value The projectId to set.
     * @return This builder for chaining.
     */
    public Builder setProjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 命令上下文（部分命令需要）
     * </pre>
     *
     * <code>string project_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectId() {
      
      projectId_ = getDefaultInstance().getProjectId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 命令上下文（部分命令需要）
     * </pre>
     *
     * <code>string project_id = 2;</code>
     * @param value The bytes for projectId to set.
     * @return This builder for chaining.
     */
    public Builder setProjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chapterId_ = "";
    /**
     * <code>string chapter_id = 3;</code>
     * @return The chapterId.
     */
    public java.lang.String getChapterId() {
      java.lang.Object ref = chapterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chapterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chapter_id = 3;</code>
     * @return The bytes for chapterId.
     */
    public com.google.protobuf.ByteString
        getChapterIdBytes() {
      java.lang.Object ref = chapterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chapterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chapter_id = 3;</code>
     * @param value The chapterId to set.
     * @return This builder for chaining.
     */
    public Builder setChapterId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chapterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chapter_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChapterId() {
      
      chapterId_ = getDefaultInstance().getChapterId();
      onChanged();
      return this;
    }
    /**
     * <code>string chapter_id = 3;</code>
     * @param value The bytes for chapterId to set.
     * @return This builder for chaining.
     */
    public Builder setChapterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chapterId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<p2pws.novel.KeyValue> args_ =
      java.util.Collections.emptyList();
    private void ensureArgsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        args_ = new java.util.ArrayList<p2pws.novel.KeyValue>(args_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        p2pws.novel.KeyValue, p2pws.novel.KeyValue.Builder, p2pws.novel.KeyValueOrBuilder> argsBuilder_;

    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public java.util.List<p2pws.novel.KeyValue> getArgsList() {
      if (argsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(args_);
      } else {
        return argsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public int getArgsCount() {
      if (argsBuilder_ == null) {
        return args_.size();
      } else {
        return argsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public p2pws.novel.KeyValue getArgs(int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);
      } else {
        return argsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder setArgs(
        int index, p2pws.novel.KeyValue value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
      } else {
        argsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder setArgs(
        int index, p2pws.novel.KeyValue.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.set(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder addArgs(p2pws.novel.KeyValue value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
      } else {
        argsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder addArgs(
        int index, p2pws.novel.KeyValue value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(index, value);
        onChanged();
      } else {
        argsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder addArgs(
        p2pws.novel.KeyValue.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder addArgs(
        int index, p2pws.novel.KeyValue.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends p2pws.novel.KeyValue> values) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
      } else {
        argsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder clearArgs() {
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        argsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public Builder removeArgs(int index) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.remove(index);
        onChanged();
      } else {
        argsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public p2pws.novel.KeyValue.Builder getArgsBuilder(
        int index) {
      return getArgsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public p2pws.novel.KeyValueOrBuilder getArgsOrBuilder(
        int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);  } else {
        return argsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public java.util.List<? extends p2pws.novel.KeyValueOrBuilder> 
         getArgsOrBuilderList() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(args_);
      }
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public p2pws.novel.KeyValue.Builder addArgsBuilder() {
      return getArgsFieldBuilder().addBuilder(
          p2pws.novel.KeyValue.getDefaultInstance());
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public p2pws.novel.KeyValue.Builder addArgsBuilder(
        int index) {
      return getArgsFieldBuilder().addBuilder(
          index, p2pws.novel.KeyValue.getDefaultInstance());
    }
    /**
     * <pre>
     * 通用参数（与具体 command_id 配套，定义在 Server 端 Java 注释里）
     * </pre>
     *
     * <code>repeated .p2pws.novel.KeyValue args = 4;</code>
     */
    public java.util.List<p2pws.novel.KeyValue.Builder> 
         getArgsBuilderList() {
      return getArgsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        p2pws.novel.KeyValue, p2pws.novel.KeyValue.Builder, p2pws.novel.KeyValueOrBuilder> 
        getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            p2pws.novel.KeyValue, p2pws.novel.KeyValue.Builder, p2pws.novel.KeyValueOrBuilder>(
                args_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        args_ = null;
      }
      return argsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:p2pws.novel.NovelWriterCommandRequest)
  }

  // @@protoc_insertion_point(class_scope:p2pws.novel.NovelWriterCommandRequest)
  private static final p2pws.novel.NovelWriterCommandRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new p2pws.novel.NovelWriterCommandRequest();
  }

  public static p2pws.novel.NovelWriterCommandRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NovelWriterCommandRequest>
      PARSER = new com.google.protobuf.AbstractParser<NovelWriterCommandRequest>() {
    @java.lang.Override
    public NovelWriterCommandRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NovelWriterCommandRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NovelWriterCommandRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NovelWriterCommandRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public p2pws.novel.NovelWriterCommandRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

