# properties
proxyEnable = true
imaggaProxyEnable = false
network.proxy.type.socks = false
network.proxy.type = 1
network.proxy.http = gs-server
network.proxy.http_port = 1080
network.proxy.no_proxies_on = localhost
# p2p.receive.buffer.size




