
package com.q3lives.ds.annotation.query;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * 一对多targetEntity属性自动封装为以逗号分隔的字符串的vo单个字段(对应页面多选框数组形式)
 *
 * @author iamkarl@163.com
 * @since 2020-10-13
 */
@Target(FIELD)
@Retention(RUNTIME)
public @interface TransformStringArray {

     /**
     * 包含注解本身所属字段名，以及指定的一个或多个属性名的 entity class 
     * 
     * @return 
     */
    Class targetEntity();
    
    /**
     * 用于转换操作的vo class的属性名。
     * @return
     */
    String voProp();
    
    /**
     * 用于转换操作的target entity class的属性名。
     * @return
     */
    String fromProp();
    
    /**
     * 用于转换操作的target entity class的属性名。
     * @return
     */
    String toProp();
  
           /**
     * (Optional) Whether the column is included in
     * SQL INSERT statements generated by the persistence
     * provider.
     * @return 
     */
   // boolean insertable() default true;

    /**
     * (Optional) Whether the column is included in
     * SQL UPDATE statements generated by the persistence
     * provider.
     * @return 
     */
    //boolean updatable() default true;
}
